# This is a basic workflow that is manually triggered

name: Build-and-Deploy
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-jar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

    # Use a specific Java version to build the application
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
           java-version: '17'
           distribution: 'temurin'

      - name: Build the Java application
        run: mvn clean install

      - name: List build directory
        run: ls -la target

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mpesasimulator
          path: target/MpesaSimulatorDemo-0.0.1-SNAPSHOT.jar
          if-no-files-found: warn
          include-hidden-files: false

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: mpesasimulator
          path: ./

      - name: List build directory
        run: ls -la target

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mpesasimulator:latest .

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub (or any other Docker registry)
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mpesasimulator:latest
